name: Build PR Preview

on:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Build Roq
        run: QUARKUS_ROQ_GENERATOR_BATCH=true mvn -B package quarkus:run

      - name: Store PR id
        run: |
          mkdir -p ./target/roq/docs
          echo ${{ github.event.number }} > ./target/roq/docs/pr-id.txt

#      - name: Publishing docs
#        uses: actions/upload-artifact@v4
#        with:
#          name: docs
#          path: ./target/roq
#          retention-days: 3

      - name: Build blog
        uses: quarkiverse/quarkus-roq@main
        with:
          setup-java: 'false'
          github-pages: 'false'
          site-directory: '.'
          site-future: 'true'
          maven-executable: 'mvn'

      - name: Publishing blog
        uses: actions/upload-artifact@v4
        with:
          name: blog
          path: ./target/roq
          retention-days: 3